import type { GateCriterionDefinition, GateDefinition } from "./gates";
import type { PackageStageId } from "./packages";
import type { ProjectStageId } from "./projects";

export const governanceTemplateVersion = 2;
const projectBaselineApprovalTemplateVersion = 3;

export type DeliverableTemplateDefinition = {
  id: string;
  title: string;
  description: string;
  criterionIds?: string[];
};

export type GovernanceGateTemplate<StageId extends string> = GateDefinition<StageId> & {
  deliverables: DeliverableTemplateDefinition[];
};

const criterion = (
  id: string,
  description: string,
  previousDescriptions?: readonly string[],
): GateCriterionDefinition => ({ id, description, previousDescriptions });
const deliverable = (
  id: string,
  title: string,
  description = "",
  criterionIds?: string[],
): DeliverableTemplateDefinition => ({
  id,
  title,
  description,
  criterionIds,
});

export const projectGateTemplates: GovernanceGateTemplate<ProjectStageId>[] = [
  {
    id: "project_authorization",
    templateVersion: governanceTemplateVersion,
    name: "Project Authorization",
    stageId: "initiation",
    criteria: [
      criterion("business_need_defined", "Business need/problem is clearly defined."),
      criterion("objectives_benefits_defined", "Project objectives and expected benefits are sufficiently defined."),
      criterion("preliminary_scope_defined", "Preliminary Project Scope is defined."),
      criterion("assumptions_exclusions_understood", "Major assumptions and exclusions are understood."),
      criterion("initial_budget_available", "Initial Budget estimate is available."),
      criterion("initial_schedule_available", "Initial Schedule/milestones and required completion date are available."),
      criterion("initial_risks_assessed", "Initial Project Risks have been assessed."),
      criterion("key_stakeholders_identified", "Key stakeholders are identified."),
      criterion("project_organization_established", "Project Manager and initial Project organization are established."),
      criterion("initial_raci_defined", "Initial Project RACI is sufficiently defined."),
      criterion("initiation_actions_resolved", "Critical Initiation Actions are closed or accepted."),
      criterion("initiation_decisions_documented", "Key Decisions made during Initiation are documented."),
      criterion("project_justified", "Project remains justified based on current information."),
    ],
    deliverables: [
      deliverable("project_charter", "Project Charter / Project Brief / One-pager"),
      deliverable("preliminary_project_scope", "Preliminary Project Scope"),
      deliverable("initial_budget", "Initial Budget"),
      deliverable("initial_master_schedule", "Initial Master Schedule / Milestone Plan"),
      deliverable("initial_project_raci", "Initial Project RACI"),
      deliverable("business_case_roi", "Business Case / ROI — where applicable"),
    ],
  },
  {
    id: "project_baseline_approval",
    templateVersion: projectBaselineApprovalTemplateVersion,
    name: "Project Baseline Approval",
    stageId: "definition_design",
    criteria: [
      criterion("project_scope_approved", "Overall Project Scope is defined and approved."),
      criterion("project_requirements_approved", "Project Requirements / URS are sufficiently defined and approved."),
      criterion("concept_design_mature", "Concept / Basic Design is sufficiently mature."),
      criterion("master_layout_approved", "Master Layout is approved at the required maturity."),
      criterion("package_breakdown_defined", "Package breakdown is sufficiently defined."),
      criterion("package_interfaces_identified", "Package boundaries and major Interfaces are identified."),
      criterion("package_strategies_defined", "Package execution strategies are sufficiently defined for the current Project maturity."),
      criterion("project_budget_developed", "Project Budget is sufficiently developed."),
      criterion("master_schedule_developed", "Master Schedule is sufficiently developed."),
      criterion("project_governance_established", "Project RACI and governance structure are established."),
      criterion(
        "escalation_structure_defined",
        "Project governance, meeting and escalation structure is defined, including the applicable Governance Tiers.",
        ["Governance Tiers / escalation structure are defined."],
      ),
      criterion("project_risks_assessed", "Major Project Risks have been assessed and responses assigned."),
      criterion("critical_issues_understood", "Critical Issues are understood."),
      criterion("baseline_actions_resolved", "Critical Actions required for baselining are closed or accepted."),
      criterion("procurement_strategy_defined", "Procurement Strategy is defined."),
      criterion("validation_strategy_defined", "Validation Strategy is defined where applicable."),
      criterion("traceability_approach_established", "Requirements Traceability approach is established where applicable."),
      criterion("baselines_ready", "Scope, Cost and Schedule are ready to be formally baselined."),
      criterion("business_case_justified", "Project remains justified against the updated Business Case."),
    ],
    deliverables: [
      deliverable("approved_project_scope", "Approved Project Scope"),
      deliverable("approved_overall_requirements", "Approved URS / Overall Requirements"),
      deliverable("concept_basic_design", "Concept / Basic Design"),
      deliverable("master_layout", "Master Layout"),
      deliverable("package_breakdown_scope_structure", "Package Breakdown / Scope Structure"),
      deliverable("project_budget_baseline_ready", "Project Budget ready for baseline"),
      deliverable("master_schedule_baseline_ready", "Master Schedule ready for baseline"),
      deliverable("project_raci", "Project RACI"),
      deliverable(
        "project_governance_escalation_plan",
        "Project Governance & Escalation Plan",
        "Defines the Project Governance Tiers; purpose and scope of each Tier; escalation paths between Tiers; decision authority; meeting structure and cadence; typical participants and roles; topics and registers reviewed at each Tier; and escalation rules and triggers.",
        ["project_governance_established", "escalation_structure_defined"],
      ),
      deliverable("procurement_execution_strategy", "Procurement / Execution Strategy"),
      deliverable("initial_interface_structure", "Interface Definition / Initial Interface Structure"),
      deliverable("validation_strategy_plan", "Validation Strategy / Plan — where applicable"),
      deliverable("initial_traceability_structure", "Initial RTM / Traceability Structure — where applicable"),
    ],
  },
  {
    id: "project_delivery_complete",
    templateVersion: governanceTemplateVersion,
    name: "Project Delivery Complete",
    stageId: "delivery",
    criteria: [
      criterion("packages_handover_complete", "Required Packages have reached their required handover/completion state."),
      criterion("cross_package_integration_complete", "Required cross-Package integration is complete."),
      criterion("overall_installation_complete", "Overall installation is complete where applicable."),
      criterion("overall_commissioning_complete", "Overall commissioning is complete where applicable."),
      criterion("integrated_testing_complete", "Required integrated/system testing is complete."),
      criterion("critical_snags_closed", "Critical SNAGs preventing handover are closed."),
      criterion("remaining_snags_accepted", "Remaining non-critical SNAGs are documented, owned and accepted."),
      criterion("operations_documentation_available", "Required operating and maintenance documentation is available."),
      criterion("operations_training_complete", "Required training/handover to Operations is complete."),
      criterion("package_interfaces_resolved", "Package Interfaces are resolved or formally transferred."),
      criterion("delivery_verification_evidence_available", "Requirements applicable to Delivery have appropriate Verification evidence."),
      criterion("critical_actions_controlled", "Critical open Actions do not prevent progression."),
      criterion("critical_risks_issues_controlled", "Critical Risks/Issues do not prevent progression or have been formally accepted."),
      criterion("approved_mocs_dispositioned", "All approved MOCs affecting delivered Scope have been implemented or formally dispositioned."),
      criterion("no_blocking_moc", "No unresolved MOC prevents progression."),
      criterion("delivered_scope_reconciled", "Delivered Scope has been reconciled against the Current Approved Scope."),
      criterion("forecasts_current", "Budget Forecast and Schedule Forecast are current."),
      criterion("ready_for_validation", "Equipment/system is ready for Validation where applicable."),
    ],
    deliverables: [
      deliverable("package_handover_records", "Package Handover Records"),
      deliverable("integrated_sat_evidence", "Integrated SAT / System Test Evidence — where applicable"),
      deliverable("updated_master_layout", "Updated Master Layout / appropriate as-built maturity"),
      deliverable("handover_documentation", "Handover Documentation"),
      deliverable("training_documentation", "Training Documentation"),
      deliverable("snag_overview", "Outstanding Items / SNAG Overview"),
      deliverable("updated_verification_evidence", "Updated RTM / Verification Evidence — where applicable"),
    ],
  },
  {
    id: "validation_complete",
    templateVersion: governanceTemplateVersion,
    name: "Validation Complete",
    stageId: "validation",
    criteria: [
      criterion("iq_approved", "IQ is completed and approved where applicable."),
      criterion("oq_approved", "OQ is completed and approved where applicable."),
      criterion("pq_approved", "PQ is completed and approved where applicable."),
      criterion("validation_deviations_dispositioned", "Validation deviations are closed or formally dispositioned."),
      criterion("requirements_traceability_complete", "Requirements Traceability is complete."),
      criterion("critical_requirements_evidenced", "Critical Requirements have appropriate Verification/Validation evidence."),
      criterion("validation_mocs_assessed", "Validation-related MOCs have been implemented and appropriately assessed."),
      criterion("no_invalidating_change", "No unresolved Change invalidates completed qualification evidence."),
      criterion("validation_risks_accepted", "Residual Validation Risks are understood and accepted."),
      criterion("validation_documentation_approved", "Required Validation documentation is approved."),
      criterion("system_released", "System/process is formally released where applicable."),
    ],
    deliverables: [
      deliverable("iq_protocol_report", "IQ Protocol and Report"),
      deliverable("oq_protocol_report", "OQ Protocol and Report"),
      deliverable("pq_protocol_report", "PQ Protocol and Report"),
      deliverable("validation_deviation_documentation", "Validation Deviation Documentation"),
      deliverable("final_rtm", "Final RTM"),
      deliverable("validation_summary_report", "Validation Summary Report"),
      deliverable("formal_release_evidence", "Formal Release / Approval Evidence — where applicable"),
    ],
  },
  {
    id: "project_closed",
    templateVersion: governanceTemplateVersion,
    name: "Project Closed",
    stageId: "closure",
    criteria: [
      criterion("packages_closed", "All required Packages are closed."),
      criterion("validation_complete", "Validation is complete or Not Applicable."),
      criterion("final_scope_documented", "Final Scope / as-built state is documented."),
      criterion("final_budget_established", "Final Budget position is established."),
      criterion("final_schedule_established", "Final Schedule performance is established."),
      criterion("financial_commitments_understood", "Remaining financial commitments are understood."),
      criterion("mocs_closed", "All MOCs are implemented and closed, cancelled, or formally transferred."),
      criterion("critical_actions_closed", "Critical Actions are closed."),
      criterion("remaining_actions_transferred", "Remaining Actions are formally transferred with owner/due date where applicable."),
      criterion("risks_issues_transferred", "Risks and Issues are closed or formally transferred."),
      criterion("final_decisions_documented", "Final Decisions are documented."),
      criterion("customer_operations_handover_complete", "Customer / Operations handover is complete."),
      criterion("final_documents_complete", "Required final Documents are complete."),
      criterion("warranty_ownership_established", "Warranty/follow-up ownership is established."),
      criterion("lessons_learned_captured", "Lessons Learned have been captured."),
      criterion("project_performance_evaluated", "Project performance has been evaluated."),
      criterion("project_archive_complete", "Internal Project Archive is complete."),
      criterion("customer_handover_package_complete", "Customer Handover Package is complete where required."),
    ],
    deliverables: [
      deliverable("final_as_built_scope", "Final / As-Built Project Scope"),
      deliverable("final_master_layout", "Final Master Layout"),
      deliverable("final_budget_cost_report", "Final Budget / Cost Report"),
      deliverable("final_schedule_performance_report", "Final Schedule Performance Report"),
      deliverable("final_rtm", "Final RTM — where applicable"),
      deliverable("final_handover_record", "Final Handover Record"),
      deliverable("lessons_learned", "Lessons Learned"),
      deliverable("project_evaluation", "Post-Mortem / Project Evaluation"),
      deliverable("internal_project_archive", "Internal Project Archive"),
      deliverable("customer_handover_package", "Customer Handover Package — where applicable"),
    ],
  },
];

export const packageGateTemplates: GovernanceGateTemplate<PackageStageId>[] = [
  {
    id: "definition_complete",
    templateVersion: governanceTemplateVersion,
    name: "Definition Complete / Ready for Execution Strategy",
    stageId: "definition",
    criteria: [
      criterion("package_scope_defined", "Package Scope is sufficiently defined."),
      criterion("package_requirements_defined", "Package Requirements are sufficiently defined."),
      criterion("technical_specification_mature", "Technical Specification is sufficiently mature for the intended next step."),
      criterion("package_boundaries_defined", "Package boundaries are defined."),
      criterion("package_interfaces_identified", "Package Interfaces are identified."),
      criterion("package_owner_identified", "Package owner is identified."),
      criterion("execution_responsibilities_defined", "Package execution responsibilities are defined."),
      criterion("package_raci_defined", "Package RACI is sufficiently defined."),
      criterion("package_budget_identified", "Required Budget is identified within the Project Budget."),
      criterion("delivery_dates_defined", "Required delivery dates and key milestones are defined."),
      criterion("package_risks_assessed", "Major Package Risks have been assessed."),
      criterion("fat_sat_requirements_defined", "FAT/SAT requirements are defined where applicable."),
      criterion("documentation_requirements_defined", "Documentation requirements are defined."),
      criterion("validation_support_defined", "Validation support requirements are defined where applicable."),
      criterion("internal_resource_demand_understood", "Preliminary Internal Resource demand is understood where Internal execution remains an option."),
      criterion("critical_package_actions_controlled", "Critical Package Actions do not prevent progression."),
      criterion("execution_strategy_decision_ready", "Package is sufficiently defined to make/progress the Execution Strategy decision."),
    ],
    deliverables: [
      deliverable("package_scope", "Package Scope"),
      deliverable("package_requirements", "Package Requirements"),
      deliverable("technical_specification", "Technical Specification"),
      deliverable("package_raci", "Package RACI / Package Organization"),
      deliverable("package_interface_definition", "Package Interface Definition"),
      deliverable("package_milestone_requirements", "Package Milestone Requirements"),
      deliverable("preliminary_internal_resource_estimate", "Preliminary Internal Resource Estimate — where applicable"),
    ],
  },
  {
    id: "execution_strategy_selection",
    templateVersion: governanceTemplateVersion,
    name: "Execution Strategy Selection",
    stageId: "tendering",
    criteria: [
      criterion("tender_package_defined", "Tender / RFQ Package was sufficiently defined."),
      criterion("external_proposals_received", "Required external proposals have been received where applicable."),
      criterion("supplier_compliance_evaluated", "Supplier technical compliance has been evaluated."),
      criterion("supplier_deviations_understood", "Material supplier deviations and clarifications are understood."),
      criterion("internal_feasibility_assessed", "Internal execution feasibility has been assessed where Internal execution remains an option."),
      criterion("internal_capacity_understood", "Required Internal Resources and capacity are understood."),
      criterion("schedule_implications_understood", "Internal versus External Schedule implications are understood."),
      criterion("cost_implications_understood", "Internal versus External Cost implications are sufficiently understood."),
      criterion("execution_risks_assessed", "Execution Risks have been assessed."),
      criterion("key_interfaces_understood", "Key Interfaces are understood."),
      criterion("execution_model_justified", "Recommended Execution Model is justified."),
      criterion("execution_model_approved", "Required stakeholders approve the recommended Execution Model."),
      criterion("selection_actions_resolved", "Critical Actions preventing selection are closed or accepted."),
    ],
    deliverables: [
      deliverable("rfq_tender_package", "RFQ / Tender Package"),
      deliverable("supplier_proposals", "Supplier Proposal(s) — where applicable"),
      deliverable("technical_evaluation", "Technical Evaluation / TECO — where applicable"),
      deliverable("internal_execution_proposal", "Internal Execution Proposal — where applicable"),
      deliverable("internal_resource_estimate", "Internal Resource Estimate — where applicable"),
      deliverable("make_or_buy_recommendation", "Execution Strategy / Make-or-Buy Recommendation"),
    ],
  },
  {
    id: "contract_award",
    templateVersion: governanceTemplateVersion,
    name: "Contract Award",
    stageId: "procurement",
    criteria: [
      criterion("preferred_supplier_approved", "Preferred supplier has been technically approved."),
      criterion("final_package_scope_clear", "Final Package Scope is clear."),
      criterion("technical_deviations_resolved", "Technical deviations are resolved or formally accepted."),
      criterion("commercial_offer_evaluated", "Commercial offer has been evaluated."),
      criterion("negotiation_complete", "Negotiation is complete."),
      criterion("contractual_responsibilities_clear", "Contractual responsibilities are clear."),
      criterion("contractual_interfaces_clear", "Interfaces and Scope boundaries are contractually clear."),
      criterion("contract_schedule_acceptable", "Contract Schedule is acceptable."),
      criterion("commercial_value_approved", "Final commercial value is within Current Approved Budget or an approved MOC exists."),
      criterion("contractual_risks_understood", "Commercial / contractual Risks are understood."),
      criterion("required_approvals_obtained", "Required approvals have been obtained."),
      criterion("purchase_documentation_ready", "Purchase / contract documentation is ready."),
      criterion("approved_changes_reflected", "Relevant approved Changes/MOCs are reflected in the contractual Scope where applicable."),
    ],
    deliverables: [
      deliverable("final_technical_evaluation", "Final Technical Evaluation / TECO"),
      deliverable("commercial_comparison", "Commercial Comparison"),
      deliverable("commercial_recommendation", "Commercial Recommendation"),
      deliverable("contract_cnd", "Contract / CND"),
      deliverable("cca_loi", "CCA / LOI — where applicable"),
      deliverable("purchase_request", "Purchase Request"),
      deliverable("purchase_order", "Purchase Order"),
      deliverable("contractual_scope", "Contractual Scope"),
      deliverable("contractual_schedule", "Contractual Schedule"),
    ],
  },
  {
    id: "package_handover",
    templateVersion: governanceTemplateVersion,
    name: "Package Handover / Execution Complete",
    stageId: "execution",
    criteria: [
      criterion("engineering_design_complete", "Required engineering/design is complete."),
      criterion("implementation_complete", "Required implementation/manufacturing is complete."),
      criterion("fat_testing_complete", "FAT/internal testing is complete where applicable."),
      criterion("installation_complete", "Installation is complete where applicable."),
      criterion("commissioning_complete", "Commissioning is complete where applicable."),
      criterion("sat_verification_complete", "SAT/Verification is complete where applicable."),
      criterion("critical_snags_closed", "Critical SNAGs are closed."),
      criterion("remaining_snags_assigned", "Remaining SNAGs are documented, accepted and assigned."),
      criterion("training_complete", "Required training is complete."),
      criterion("manuals_available", "Required manuals/documentation are available."),
      criterion("as_built_controlled", "As-built documentation is available at the required maturity or finalization is controlled."),
      criterion("package_verification_evidence_available", "Package Requirements have appropriate Verification evidence."),
      criterion("package_interfaces_resolved", "Package Interfaces are resolved."),
      criterion("package_mocs_implemented", "Approved Package-related MOCs have been implemented."),
      criterion("no_blocking_moc", "No unresolved MOC prevents handover."),
      criterion("actions_risks_issues_controlled", "Critical Actions/Risks/Issues do not prevent handover."),
      criterion("package_ready_for_use", "Package is safe and ready for intended use / next Project activity."),
      criterion("handover_accepted", "Receiving organization accepts handover."),
    ],
    deliverables: [
      deliverable("approved_design_documentation", "Approved Design Documentation"),
      deliverable("fat_protocol_report", "FAT Protocol / Report — where applicable"),
      deliverable("installation_documentation", "Installation Documentation — where applicable"),
      deliverable("commissioning_documentation", "Commissioning Documentation — where applicable"),
      deliverable("sat_protocol_report", "SAT Protocol / Report — where applicable"),
      deliverable("training_records", "Training Records — where applicable"),
      deliverable("manuals", "Manuals"),
      deliverable("spare_parts_information", "Spare-Parts Information — where applicable"),
      deliverable("snag_punch_list", "SNAG / Punch List"),
      deliverable("handover_record", "Handover Record"),
      deliverable("provisional_acceptance", "Provisional Acceptance Documentation — where applicable"),
      deliverable("updated_as_built_documentation", "Updated / As-Built Documentation"),
    ],
  },
  {
    id: "package_closed",
    templateVersion: governanceTemplateVersion,
    name: "Package Closed",
    stageId: "closure",
    criteria: [
      criterion("actions_snags_resolved", "Remaining Package Actions/SNAGs are closed or formally transferred."),
      criterion("as_built_documentation_complete", "Final as-built documentation is complete."),
      criterion("package_verification_complete", "Package Requirements / Verification status is complete."),
      criterion("package_mocs_closed", "Package-related MOCs are implemented and closed or formally transferred."),
      criterion("package_cost_established", "Final Package Cost position is established."),
      criterion("final_acceptance_complete", "Final Acceptance is complete where applicable."),
      criterion("warranty_documented", "Warranty information is documented where applicable."),
      criterion("supplier_obligations_complete", "Supplier obligations are complete where applicable."),
      criterion("supplier_performance_evaluated", "Supplier performance has been evaluated where applicable."),
      criterion("package_risks_issues_resolved", "Package Risks/Issues are closed or transferred."),
      criterion("package_lessons_captured", "Package Lessons Learned are captured where relevant."),
      criterion("package_documents_archive_ready", "Required Package Documents are ready for Project Archive/Handover."),
    ],
    deliverables: [
      deliverable("final_as_built_package", "Final As-Built Package"),
      deliverable("final_package_cost_summary", "Final Package Cost Summary"),
      deliverable("final_acceptance_documentation", "Final Acceptance Documentation — where applicable"),
      deliverable("warranty_documentation", "Warranty Documentation — where applicable"),
      deliverable("supplier_performance_evaluation", "Supplier Performance Evaluation — where applicable"),
      deliverable("package_lessons_learned", "Package Lessons Learned — where applicable"),
    ],
  },
];

export function getProjectGateTemplates(validationRequired: boolean) {
  return projectGateTemplates.filter((template) => validationRequired || template.stageId !== "validation");
}
